My_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('', include('blog_app.urls')),
 
       
]
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog_app/urls.py
from django.urls import path
from .import views
from .views import CreateBlog,BlogList, UpdateBlog

app_name='blog_app'

urlpatterns = [
    path('', views.HomePage, name='HomePage'),
    path('all/', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(),name='create_blog' ),
    path('details/<slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blog/', views.MyBlogs.as_view(), name='my_blog'),
    path('edit-blog/<int:pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
    path('delete-blog/<int:pk>/', views.RemovePost.as_view(), name='delete_blog'),
    path('reader/', views.Read_page, name='Read_page'),
    
]

login_app/urls.py
from django.urls import path
from .import views

app_name='login_app'

urlpatterns = [
    path('', views.User_login, name='User_login'),
    path('signup/', views.SignUp, name='SignUp'),
    path('logout/', views.User_logout, name='User_logout'),
    path('profile/', views.User_profile, name='User_profile'),
    path('edit_profile/', views.User_change, name='User_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add_pro/', views.add_pro_pic, name='add_pro_pic'),
    path('change_pro/', views.change_pic, name='change_pic'),
    
]

blog_app/models.py
from distutils.command.upload import upload
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name="Put a Title")
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name="What is on your mind?")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name="Image")
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish_date',]

    def __str__(self):
        return self.blog_title


class Comment(models.Model):
    blog=models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='blog_comment')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_comment')
    comment=models.TextField()
    comment_date=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-comment_date',]

    def __str__(self):
        return self.comment  


class Likes(models.Model):
    blog=models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='liked_blog')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='liker_user')
    
    def __str__(self):
        return self.user + "likes"+ self.blog

blog_app/forms.py
from dataclasses import field
from django import forms
from .models import Likes , Comment,Blog



class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('comment',)


class UpdatePost(forms.ModelForm):
    class Meta:
        model=Blog
        fields=('blog_title','blog_content','blog_image')

My_Blog/views.py
from django import http
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect

# Create your views here.
def Index(request):
    return HttpResponseRedirect(reverse('blog_app:blog_list'))

blog_app/views.py
from ast import Return
from dataclasses import field
from re import template
import re
from tkinter.messagebox import RETRY
from urllib import request
from django.shortcuts import render,HttpResponseRedirect, HttpResponse, redirect
from django.views.generic import CreateView, UpdateView, ListView,DetailView,View ,TemplateView,DeleteView
from django.urls import reverse , reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
from django import forms
from blog_app.models import Blog,Likes,Comment
from .forms import CommentForm, UpdatePost
# Create your views here.
# def Blog_list(request):
#     return render(request, 'blog_app/blog_list.html')


class CreateBlog(LoginRequiredMixin ,CreateView):
    model = Blog
    template_name = 'blog_app/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image',)
    
    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('blog_app:HomePage'))


class BlogList(ListView):
    context_object_name="blogs"
    model = Blog
    template_name = 'blog_app/blog_list.html'
    # queryset = Blog.objects.order_by('-publish_date') #for  blog post time ordering 



@login_required
def blog_details(request,slug):
    blog = Blog.objects.get(slug=slug)
    comment_form=CommentForm()
    already_liked = Likes.objects.filter(blog=blog, user=request.user)
    if already_liked:
        liked =True
    else:
        liked= False

    if request.method == "POST":
        comment_form=CommentForm(request.POST)
        if comment_form.is_valid():
            comment=comment_form.save(commit=False)
            comment.user=request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('blog_app:blog_list'))

    details_context={
        'title':'Blog Details',
        'blog':blog,
        'comment_form':comment_form,
        'liked__':liked
    }
    return render(request, 'blog_app/blog_details.html',context=details_context)

@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked_post= Likes(blog=blog, user=user)
        liked_post.save()
    return redirect('blog_app:blog_list')

@login_required
def unliked(request, pk):
    blog= Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
    
    return redirect('blog_app:blog_list')


class MyBlogs(LoginRequiredMixin, TemplateView):
    template_name='blog_app/my_blogs.html'

       
class UpdateBlog(LoginRequiredMixin,UpdateView):
    model = Blog
    template_name='blog_app/edit_blog.html'
    fields=['blog_title','blog_image','blog_content']

    def get_success_url(self):
        return reverse_lazy('blog_app:my_blog')
    
class RemovePost(LoginRequiredMixin, DeleteView):
    model = Blog
    template_name = "blog_app/delete_blog.html"
    success_url = reverse_lazy('blog_app:my_blog')
   
#for paginator
from django.core.paginator import Paginator
def HomePage(request):
    post_list=Blog.objects.all()
    blog_paginator=Paginator(post_list, 5)
    page_number = request.GET.get('page')
    pag_obj = blog_paginator.get_page(page_number)
    post_list_con={
        "title":"Blog_post",
        "blogs_title_obj":post_list,
        'post_object':pag_obj
    }
    return render(request,'blog_app/homepage.html', context=post_list_con)


def Read_page(request):
    read_context={
        "title":"Reader",
    }
    return render (request, 'blog_app/Read_more.html', context=read_context)

templates/blog_app/Read_more.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    {{title}}
{% endblock title_block %}



{% block content_block %}
    <div class="login_page" style="width: 100%; height:100vh;">


    <h2 style="text-align: center;">If You want to read full articale you should <a href="{% url 'login_app:User_login' %}">Login</a> or <a href="{% url 'login_app:SignUp' %}">Sign Up</a> first otherwise it's boyend fretures</h2><hr>
        <div class="read_more text-center">
            <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus nemo vel rem alias, itaque magni explicabo eum dolores? Cupiditate ratione excepturi maiores fuga voluptas, obcaecati labore ea quidem quasi deserunt quos fugit, et perspiciatis ipsum doloremque quis consectetur eius eum itaque eaque sequi repellendus quam beatae. Reiciendis animi suscipit quasi?</small>
            <br><br>
            <p>Login your Account!</p>
            <a href="{% url 'login_app:User_login' %}" class="btn btn-success px-3 py-2">Login</a><br><br><br>
            <p>Haven't an account? </p>
            <a href="{% url 'login_app:SignUp' %}" class="btn btn-success px-3 py-2">Sign Up</a>
            
            
        </div>

           

            
      
    </div>
  
{% endblock content_block %}

templates/blog_app/blog_details.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}
{{title}}
{% endblock title_block %}



{% block content_block %}



<div class="row">
    <div class="col-sm-5">
        <h3>{{blog.blog_title}}</h3>
        <h6>Posted by: <a href="#">@{{blog.author}}</a></h6>
        <h6><i>Published On: {{blog.publish_date}}</i></h6>
        <h6><i>Update On: {{blog.update_date}}</i></h6>
        <h6>{{blog.liked_blog.count}} likes | {{blog.blog_comment.count}} comments</h6>

    </div>
    <div class="col-sm-7 pl-5">
        <img src="/media/{{ blog.blog_image }}" alt="{{blog.blog_title}}" width="100%">
        
    </div><br><br>
    
</div>    
<div class="contect_sec p-5">
    <p>{{blog.blog_content|linebreaks}}</p>
</div><hr>
<div class="liked_section pl-5" >
    {% if not liked__ %}
    <a href="{% url 'blog_app:liked_post' pk=blog.pk %}" >
        <i class="far fa-thumbs-down fa-2x"></i>
    </a>
    {% else %}
    <a href="{% url 'blog_app:unliked_post' pk=blog.pk %}"> 
        <i class="far fa-thumbs-up fa-2x" aria-hidden="true"></i>
    </a>
    {% endif  %}
    
</div>
<div class="row">
    <div class="col-sm-6">
        <hr>
       <b> <h5>Comments:</b></h5>
       
    </div>
    <div class="col-sm-6">
        <form action="" method="POST">
            {% csrf_token %}
            {{comment_form|crispy}}
            {% csrf_token %}
            <button type="submit" class="btn btn-warning btn-sm m-3 p-2">comment</button>
        </form>
        
    </div>
</div>
<br><br>
<hr>

<div class="comment">
    {% for comment in blog.blog_comment.all %}
    <a href="">@{{comment.user}}</a><br>
    <h6>{{comment.comment_date}}</h6>
    <p>{{comment.comment}}</p><br><br>
    {% endfor %} 

    

</div>



<br><br>
<br>

{% endblock content_block %}

templates/blog_app/blog_list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% load crispy_forms_tags %}
{% block title_block %}
    {{title}}
{% endblock title_block %}



{% block content_block %}
        <!-- <h1 class="text-center">Blog List page</h1> -->
        {% for blog in blogs %}
        <h3>{{blog.blog_title}}</h3>
        <h6><i>{{blog.publish_date}}</i></h6>
        <div class="row">
            <div class="col-sm-5">
                <img src="/media/{{ blog.blog_image }}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
            </div>
            <div class="col-sm-7">
                {% if request.user.is_authenticated %}
                <p>{{blog.blog_content|range_filter|linebreaks}}<b> <a href="{% url 'blog_app:blog_details' blog.slug %}" style="color: #ff8c00;" >Read More</a></b></p>
                {% else %}
                <p>{{blog.blog_content|range_filter|linebreaks}}<b> <a href="{% url 'blog_app:Read_page' %}" style="color: #ff8c00;" >Read More</a></b></p>
                {% endif %}

                <h6>Posted by: <a href="#">@{{blog.author}}</a></h6>
                <h6>{{blog.liked_blog.count}} likes | {{blog.blog_comment.count}} comments</h6>

            </div>
        </div>
        <hr>
        

        {% endfor %}
        
        
{% endblock content_block %}

<!-- <a href="{% url 'blog_app:blog_details' slug=blog.slug %}">Read more</a>  -->

templates/blog_app/create_blog.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %}
    Blog_Create
{% endblock title_block %}



{% block content_block %}
        <h1 class="text-center ">Create Blog page</h1> 
        <div style="border: 2px dashed rgb(12, 3, 3);"></div>
        <br> <br>

        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-success px-4 py-3 m-3 p-2">Publish</button>
        </form>

{% endblock content_block %}

templates/blog_app/delete_blog.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% load crispy_forms_tags %}
{% block title_block %}
    {{title}}
{% endblock title_block %}



{% block content_block %}

<h5>Delete You Blog!! </h5> 
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    <h4>Are You sure ?</h4>
    <button type="submit" name="button" class="btn btn-danger">Delete </button>

</form>
        
{% endblock content_block %}

templates/blog_app/edit_blog.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    {{blog.blog_title}}
{% endblock title_block %}



{% block content_block %}

        <h1 class="text-center">Edit Blog </h1> 
        {% if blog.author == user %}
        <form method="POST" enctype="multipart/form-data" >
            {{form|crispy}}
            {% csrf_token %}

            <button type="submit" name="button" class="btn btn-success">Publish </button>
            <a href="{% url 'blog_app:delete_blog' blog.pk %}" class="btn btn-danger p-3 m-4">Remove Post</a>

        </form>
        {% else %}
        <p>Your are not allowed to view this page. 404</p>
        {% endif %}

{% endblock content_block %}

templates/blog_app/homepage.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% load crispy_forms_tags %}
{% block title_block %}
    {{title}}
{% endblock title_block %}



{% block content_fluid_block %}
        <!-- <h1 class="text-center">Blog List page</h1> -->
       
        <div class="main_content m-0" style="padding: 0px 70px 60px 60px;" >
            
            <div class="col-sm-9 " style="padding:0px 40px 20px 30px;">
                {% for blog in post_object %}
                <h3>{{blog.blog_title}}</h3>
                <h6><i>{{blog.publish_date}}</i></h6>
                <div class="row" >
                    <div class="col-sm-5" style="padding-bottom:30px;">
                        <img src="/media/{{ blog.blog_image }}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
                    </div>
                    <div class="col-sm-7">
                        {% if request.user.is_authenticated %}
                        <p style="text-align: justify;">{{blog.blog_content|range_filter|linebreaks}}<b> <a href="{% url 'blog_app:blog_details' blog.slug %}" style="color: #ff8c00;" >Read More</a></b></p>
                        {% else %}
                        <p>{{blog.blog_content|range_filter|linebreaks}}<b> <a href="{% url 'blog_app:Read_page' %}" style="color: #ff8c00;" >Read More</a></b></p>
                        {% endif %}
                        <h6>Posted by: <a href="#">@{{blog.author}}</a></h6>
                        <h6>{{blog.liked_blog.count}} likes | {{blog.blog_comment.count}} comments</h6>

                    </div>
                </div>
                {% endfor %}
                <hr>
            </div>
            <div class="col-sm-3 p-2">
                {% for blog in blogs_title_obj %}
                {% if request.user.is_authenticated %}
                <a href="{% url 'blog_app:blog_details' blog.slug %}" ><h3 style="font-size: 14px;">{{blog.blog_title}}</h3></a>
                    
                <a href="{% url 'blog_app:blog_details' blog.slug %}" style="color: #905105; font-size: 12px;" >Read More</a></b>
                {% else %}
                <a href="{% url 'blog_app:blog_list'  %}" ><h3 style="font-size: 14px;">{{blog.blog_title}}</h3></a>
                    
                <a href="{% url 'blog_app:Read_page'  %}" style="color: #905105; font-size: 12px;" >Read More</a></b>

                {% endif %}
                <hr>
                {% endfor %}
                
            </div>
            
            <br> 
            <br> 
            <br>
            <br>

        </div>
    <section>
        <div class="row text-center" style="width: 100%; font-size: large;">
            <div class="col-12 paginator">
                <span>
                    {% if post_object.has_previous %}
                    <a href="?page={{post_object.previous_page_number}}" class="btn btn-outline-success p-3">Previous</a>
                    {% endif %}

                    <span>{{post_object.number}}</span>
                    
                    <!-- {% for number_list in page_number %}
                    <span>{{number_list}}</span>
                    {% endfor %} -->

                    {% if post_object.has_next %}
                    <a href="?page={{post_object.next_page_number}}" class="btn btn-outline-success p-3">Next</a>
                    {% endif %}
                </span>
            </div>
        </div><br><br>
    </section>
        
            
        

       
        
        
    {% endblock content_fluid_block %}

<!-- <a href="{% url 'blog_app:blog_details' slug=blog.slug %}">Read more</a>  -->

templates/blog_app/my_blogs.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% load crispy_forms_tags %}
{% block title_block %}
{{title}}
{% endblock title_block %}



{% block content_block %}
<div class="my-blog p-3">
    {% for my_blog in user.post_author.all %}
    <h3>{{my_blog.blog_title}}</h3>
    <h6>{{my_blog.publish_date}}</h6>
    <div class="row">
        <div class="col-sm-4">
            <img src="/media/{{my_blog.blog_image}}" width="100%" alt="">
        </div><br><br>
        <div class="col-sm-8">
            <p>{{my_blog.blog_content| range_filter | linebreaks }} <a href="{% url 'blog_app:blog_details' my_blog.slug %}" style="color: #ff8c00;" >Read More</a>
            </p>
            <a href="{% url 'blog_app:edit_blog' my_blog.pk %}" class="btn btn-success p-3 m-4">Edit Post</a>
            <a href="{% url 'blog_app:delete_blog' my_blog.pk %}" class="btn btn-danger p-3 m-4">Remove Post</a>

        </div> 
    </div><hr>

    {% endfor %}
</div>
{% endblock content_block %}