My_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('login_app.urls')),
    path('', include('blog_app.urls')),
 
       
]
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

login_app/urls.py
from django.urls import path
from .import views

app_name='login_app'

urlpatterns = [
    path('', views.User_login, name='User_login'),
    path('signup/', views.SignUp, name='SignUp'),
    path('logout/', views.User_logout, name='User_logout'),
    path('profile/', views.User_profile, name='User_profile'),
    path('edit_profile/', views.User_change, name='User_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add_pro/', views.add_pro_pic, name='add_pro_pic'),
    path('change_pro/', views.change_pic, name='change_pic'),
    
]

login_app/models.py
from distutils.command.upload import upload
from pyexpat import model
from statistics import mode
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfile(models.Model):
    user=models.OneToOneField(User,related_name='user_profile',on_delete=models.CASCADE)
    profile_pic=models.ImageField(upload_to='profile_pic')

login_app/forms.py
from dataclasses import field
import email
from pyexpat import model
from re import T
from statistics import mode
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile

class SignUpForm(UserCreationForm):
    first_name=forms.CharField(max_length=50)
    last_name=forms.CharField(max_length=50)
    email=forms.EmailField(required=True)
    class Meta:
        model=User
        fields=('username', 'first_name','last_name' ,'email','password1','password2')

class User_profile_Change_form(UserChangeForm):
    class Meta:
        model=User
        fields=('username','email','first_name','last_name','password')

class ProfilePic(forms.ModelForm):
    class Meta:
        model=UserProfile
        fields=('profile_pic',)

login_app/views.py
from atexit import register
from urllib import request
from django.urls import reverse
from cmath import log
from re import A
import urllib
from django import forms
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm,SetPasswordForm
from django.contrib.auth import authenticate, login,logout

from .forms import ProfilePic, SignUpForm

# Create your views here.

# Sign up/registation session========================
def SignUp(request):
    form=SignUpForm()
    registered =False
    if request.method=="POST":
        form=SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered=True

    sign_context={
        'title':'Sign Up',
        'registered':registered,
        'Sign_form':form

    }
    return render(request,'login_app/signup.html',context=sign_context)


# Login session============================ 
from django.contrib.auth.forms import AuthenticationForm
def User_login(request):
    form=AuthenticationForm()
    if request.method == "POST":
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user=authenticate(username=username,password=password)
            if user is not None:
                login(request ,user)
                return render(request, 'login_app/profile.html')
    else:
        form=AuthenticationForm()
             
    login_context={
        "title":"Login",
        "login_form":form,
    }
    return render(request, 'login_app/login.html',context=login_context)


# Logout session==========================
def User_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog_app:HomePage'))


def User_profile(request):
    
    return render(request, 'login_app/profile.html',context={})


# Profile change session========================
from .forms import User_profile_Change_form
def User_change(request):
    current_user=request.user
    form=User_profile_Change_form(instance=current_user)
    if request.method == "POST":
        form = User_profile_Change_form(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form=User_profile_Change_form(instance=current_user)
            return HttpResponseRedirect(reverse('login_app:User_profile'))
    change_context={
        'title':'Change Profile',
        "change_form":form
    }
    return render(request, 'login_app/change_profile.html',context=change_context)
    

# Pass change session========================
def pass_change(request):
    current_user=request.user
    change=False
    form=PasswordChangeForm(current_user)
    if request.method == "POST":
        form=PasswordChangeForm(current_user,data=request.POST)
        if form.is_valid():
            form.save()
            change=True
            # return HttpResponseRedirect(reverse('login_app:User_profile'))
    pass_change_context={
        'title':'Pass Change',
        'pass_form':form,
        'changed':change
    }
    return render(request, 'login_app/change_pass.html',context=pass_change_context)




# Profile pic session========================
def add_pro_pic(request):
    form_=ProfilePic()
    if request.method == "POST":
        form_=ProfilePic(request.POST, request.FILES)
        if form_.is_valid():
            user_obj = form_.save(commit=False)
            user_obj.user=request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('login_app:User_profile'))
    pro_form={
        "title":"Profile Pic",
        'Pro_pic_frm':form_
    }
    return render(request, 'login_app/pro_pic.html',context=pro_form)


# Change Profile pic session========================
def change_pic(request):
    form__=ProfilePic(instance=request.user.user_profile)
    if request.method == "POST":
        form__ = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form__.is_valid():
            form__.save()
            return HttpResponseRedirect(reverse('login_app:User_profile'))
    pro_pic_chage={
        "title":"Chagne Pic",
        "Chang_pic_":form__,
    }
    return render(request, 'login_app/Re_change_pic.html',context=pro_pic_chage)

templates/Login_app/Profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    {{title}}
{% endblock title_block %}



{% block content_block %}

<div class="profile" style="width: 100%; height: 100vh;">

    <h2 style="text-align: center;"> Your Profile</h2><hr>
    {% if user.user_profile %}
    <img src="/media/{{user.user_profile.profile_pic}}" alt="" width="180px " class="rounded-circle"  style="border: 2px solid #ccc; position: relative;" height="180px">
    
    <a href="{% url 'login_app:change_pic' %}" class="btn bg-light" style="position: absolute; ">Change Picture</a>
    {% else %}
    <img src="/media/defult.png" alt="" class="rounded-circle" width="180px " style="border: 2px solid #ccc;" height="180px" ><br><br>
    <a href="{% url 'login_app:add_pro_pic' %}" class="btn btn-secondary">Change profile pic</a><br>
    {% endif %}
    <br><br>
    <p> Username: {{user.username}}</p>
    <p> Name: {{user.first_name}} {{user.Last_name}}</p>
    <p> Email Address: {{user.email}}</p>

    <br><br>
    <div class="edit_option">
        <span>Change Your Profile info <a href="{% url 'login_app:User_change' %}"><b>Edit Now!</b> </a> or <small> <a href="{% url 'login_app:pass_change' %}"> Change password</a> </small></span>
        <br><br>

    </div>
</div>
{% endblock content_block %}

templates/Login_app/Re_change_pic.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    {{title}}
{% endblock title_block %}



{% block content_block %}

    <h2 style="text-align: center;">Change Your Profile Pic</h2><hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <img src="/media/{{user.user_profile.profile_pic}}" alt="" width="180px " class="rounded-circle"  style="border: 2px solid #ccc; position: relative;" height="180px">
            {{Chang_pic_|crispy}}
            <button type="submit" class="btn btn-success btn-sm m-3 p-2">Change</button>
            <!-- <p>Haven't an account? <a href="{% url 'login_app:SignUp' %}">Create an Account!</a></p> -->
        </form>


    <!-- <div class="alert alert-success">
         Successfully loged! <a href="">Login Here!</a>
    </div> -->
{% endblock content_block %}

templates/Login_app/change_pass.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    {{title}}
{% endblock title_block %}


{% block content_block %}
    {% if changed %}
    <div class="alert alert-warning">
        <h3>Password changed Successfully!</h3>
    </div>
    {% endif %}
    <h2 style="text-align: center;">Change Your Password</h2><hr>
        <form method="POST">
            {% csrf_token %}
            {{pass_form|crispy}}
            <button type="submit" class="btn btn-success btn-sm m-3 p-2">Change</button>
            <!-- <p>Haven't an account? <a href="{% url 'login_app:SignUp' %}">Create an Account!</a></p> -->
        </form>


    <!-- <div class="alert alert-success">
         Successfully loged! <a href="">Login Here!</a>
    </div> -->
{% endblock content_block %}

templates/Login_app/change_profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    {{title}}
{% endblock title_block %}


{% block content_block %}

    <h2 style="text-align: center;">Edit Your Profile</h2><hr>
        <form method="POST">
            {% csrf_token %}
            {{change_form|crispy}}
            <button type="submit" class="btn btn-success btn-sm m-3 p-2">Change</button>
            <!-- <p>Haven't an account? <a href="{% url 'login_app:SignUp' %}">Create an Account!</a></p> -->
        </form>


    <!-- <div class="alert alert-success">
         Successfully loged! <a href="">Login Here!</a>
    </div> -->
{% endblock content_block %}

templates/Login_app/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    {{title}}
{% endblock title_block %}



{% block content_block %}
    <div class="login_page" style="width: 100%; height:100vh;">


    <h2 style="text-align: center;">Login Your Profile</h2><hr>
        <form action="" method="POST">
            {% csrf_token %}
            {{login_form|crispy}}
            <button type="submit" class="btn btn-success py-2 px-5">login</button>
            <p>Haven't an account? <a href="{% url 'login_app:SignUp' %}">Create an Account!</a></p>
        </form>
    </div>
  
{% endblock content_block %}

templates/Login_app/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <title>
        {% block title_block %}
            Blog 
        {% endblock title_block %}
    </title>
    

</head>
<body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a href="{% url 'home' %}" class="nav-link">Home</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item ">
                <a href="{% url 'login_app:User_logout' %}" class="nav-link"> Logout</a>
            </li>
            <li class="nav-item ">
                <a href="{% url 'login_app:User_profile' %}" class="nav-link"> Your Profile</a>
            </li>
            <li class="nav-item ">
                <a href="{% url 'login_app:User_change' %}" class="nav-link"> Edit Profile</a>
            </li>
            <li class="nav-item ">
                <a href="{% url 'login_app:User_profile' %}" class="nav-link"> 
                    {% if user.user_profile %}
                    <img src="/media/{{user.user_profile.profile_pic}}" alt="" width="30px " class="rounded-circle"  height="30px">
                    
                    {% else %}
                    <img src="/media/defult.png" alt="" class="rounded-circle" width="30px " height="30px" >
                    
                    {% endif %}
                </a>
            </li>
            {% else %}
            <li class="nav-item ">
                <a href="{% url 'login_app:SignUp' %}" class="nav-link">Create account</a>
            </li>
            <li class="nav-item ">
                <a href="{% url 'login_app:User_login' %}" class="nav-link"> Login</a>
            </li>
            {% endif %}
            
        </ul>
        
        <div class="nav-item dropdown">
            <a href="" class="nav-link dropdown-toggle" id="navbardrop" data-toggle="dropdown">{{user.username}}
            </a>
            <div class="dropdown-menu">
             
                <li class="nav-item ">
                    <a href="{% url 'login_app:User_profile' %}" class="nav-link"> Your Profile</a>
                </li>
                
                <li class="nav-item ">
                    <a href="{% url 'login_app:User_change' %}" class="nav-link"> Edit Profile</a>
                </li>
                <li class="nav-item ">
                    <a href="{% url 'login_app:User_logout' %}" class="nav-link"> Logout</a>
                </li>
            </div>
        </div>
    </nav>
    
    <div class="container pt-5">
        {% block content_block %}

        {% endblock content_block %}

    </div>
    
    

















    <!-- <script src="{% static 'js/all.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jQuery.js' %}"></script>
    <script src="{% static 'js/propper.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
     -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/Login_app/password_change.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    {{title}}
{% endblock title_block %}


{% block content_block %}

    <h2 style="text-align: center;">Change Your Password</h2><hr>
        <form method="POST">
            {% csrf_token %}
            {{change_password|crispy}}
            <button type="submit" class="btn btn-success btn-sm m-3 p-2">Change Password</button>
        </form>


    <!-- <div class="alert alert-success">
         Successfully loged! <a href="">Login Here!</a>
    </div> -->
{% endblock content_block %}

templates/Login_app/pro_pic.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    {{title}}
{% endblock title_block %}



{% block content_block %}

    <h2 style="text-align: center;">Edit Your Profile Pic</h2><hr>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{Pro_pic_frm|crispy}}
            <button type="submit" class="btn btn-success btn-sm m-3 p-2">Change</button>
            <!-- <p>Haven't an account? <a href="{% url 'login_app:SignUp' %}">Create an Account!</a></p> -->
        </form>


    <!-- <div class="alert alert-success">
         Successfully loged! <a href="">Login Here!</a>
    </div> -->
{% endblock content_block %}

templates/Login_app/signup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
    {{title}}
{% endblock title_block %}



{% block content_block %}
    {% if registered %}
    <div class="alert alert-success">
        Account Created Successfully! You can <a href="{% url 'login_app:User_login' %}">login Now!</a>
    </div>
    {% else %}
    <h2 style="text-align: center;">Create a new Account</h2><hr>
        <form action="" method="post">
            {% csrf_token %}
            {{Sign_form|crispy}}
            <button type="submit" class="btn btn-success btn-sm m-3 p-2">Create Account</button>
            <p>Already have an account? <a href="{% url 'login_app:User_login' %}">Login Here!</a></p>
        </form>
    {% endif %}
        
{% endblock content_block %}